
package com.yinfu.service.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestWebsServiceService", targetNamespace = "http://service.yinfu.com/", wsdlLocation = "http://localhost:8075/com.yinfu.service.TestWebsService?wsdl")
public class TestWebsServiceService
    extends Service
{

    private final static URL TESTWEBSSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTWEBSSERVICESERVICE_EXCEPTION;
    private final static QName TESTWEBSSERVICESERVICE_QNAME = new QName("http://service.yinfu.com/", "TestWebsServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8075/com.yinfu.service.TestWebsService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTWEBSSERVICESERVICE_WSDL_LOCATION = url;
        TESTWEBSSERVICESERVICE_EXCEPTION = e;
    }

    public TestWebsServiceService() {
        super(__getWsdlLocation(), TESTWEBSSERVICESERVICE_QNAME);
    }

    public TestWebsServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTWEBSSERVICESERVICE_QNAME, features);
    }

    public TestWebsServiceService(URL wsdlLocation) {
        super(wsdlLocation, TESTWEBSSERVICESERVICE_QNAME);
    }

    public TestWebsServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTWEBSSERVICESERVICE_QNAME, features);
    }

    public TestWebsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestWebsServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestWebsService
     */
    @WebEndpoint(name = "TestWebsServicePort")
    public TestWebsService getTestWebsServicePort() {
        return super.getPort(new QName("http://service.yinfu.com/", "TestWebsServicePort"), TestWebsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestWebsService
     */
    @WebEndpoint(name = "TestWebsServicePort")
    public TestWebsService getTestWebsServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.yinfu.com/", "TestWebsServicePort"), TestWebsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTWEBSSERVICESERVICE_EXCEPTION!= null) {
            throw TESTWEBSSERVICESERVICE_EXCEPTION;
        }
        return TESTWEBSSERVICESERVICE_WSDL_LOCATION;
    }

}
